apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: techtrends
spec:
  type: {{ .Values.type }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
    protocol: {{ .Values.protocol }}
  selector:
    app: techtrend
