apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm
    repoURL: https://github.com/sameedhayat/nd064_course_1
    targetRevision: HEAD
  syncPolicy: {}