namespace: staging

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends-staging
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    memory: 128Mi
    cpu: 500m
  limits:
    memory: 256Mi
    cpu: 1000m

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
