namespace: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: "Always"

replicaCount: 5

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111
